Glsl = """
layout(set = 0, binding = 0) uniform float iTime;
layout(set = 1, binding = 0) uniform vec2 iResolution;

layout(location = 0) out vec4 fragColor;

void main() {
    vec2 F = gl_FragCoord.xy;
    float i = 0.2; // scale factor for visual structure
    float rotationSpeed = 0.03; // tweak this for rotation speed
    float gasSpeed = 0.2; // tweak this for gas movement speed
    float a;
    vec2 r = iResolution.xy;
    vec2 p = (F + F - r) / r.y / 0.7;
    vec2 d = vec2(-1.0, 1.0);
    vec2 b = p - i * d;
    vec2 c = p * mat2(1.0, 1.0, d / (0.1 + i / dot(b, b)));

    a = dot(c, c);
    float angle = 0.5 * log(a) + iTime * rotationSpeed;
    float cosA = cos(angle);
    float sinA = sin(angle);
    mat2 rotation = mat2(cosA, sinA, -sinA, cosA);
    vec2 v = (c * rotation) / i;

    vec4 w = vec4(0.0);
    for (; i++ < 9.0; ) {
        vec2 s = sin(v);
        w += vec4(s.x, s.y, s.y, s.x) + 1.0;
        // v += 0.7 * sin(v.yx * i + iTime) / i + 0.5;
        v += 0.7 * sin(v.yx * i + iTime * gasSpeed) / i + 0.5;
    }

    i = length(sin(v / 0.3) * 0.4 + c * (3.0 + d));

    fragColor = 1.0 - exp(
        -exp(c.x * vec4(0.6, -0.4, -1.0, 0.0))
        / w
        / (2.0 + i * i / 4.0 - i)
        / (0.5 + 1.0 / a)
        / (0.03 + abs(length(p) - 0.7))
    );
}
"""
